[package]
name = "quick-and-dirty-self-updater"
version = "0.1.0"
authors = ["4 Eyes <nova185@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
